#pragma once


#define INGAME_OVERLAY_STATUS_ENABLED		REG_STATUS_ENABLED
#define INGAME_OVERLAY_STATUS_DISABLED		REG_STATUS_DISABLED

#define INGAME_OVERLAY_ANCHOR_LEFT			0x00000000
#define INGAME_OVERLAY_ANCHOR_TOP			0x00000000
#define INGAME_OVERLAY_ANCHOR_RIGHT			0x00000001
#define INGAME_OVERLAY_ANCHOR_BOTTOM		0x00000002

#define OVERLAY_HELPER_PROCESSID_ARG		L"--pid"
#define OVERLAY_HELPER_MANUAL_MAP_ARG		L"-mm"
#define OVERLAY_HELPER_DEFAULT_INJ_ARG		L"-d"

#define OVERLAY_IMAGE_DEFAULT_WIDTH			450
#define OVERLAY_IMAGE_DEFAULT_HEIGHT		450

#define APP_REG_PATH_OVERLAY					L"SOFTWARE\\Outfled\\Microphone Mute\\Overlay"
#define APP_REG_VALUE_OVERLAY_IMAGE_WIDTH		L"OverlayWidth"
#define APP_REG_VALUE_OVERLAY_IMAGE_HEIGHT		L"OverlayHeight"
#define APP_REG_VALUE_BINARY_PATH				L"BinaryPath"
#define APP_REG_VALUE_SELECTED_MODULE			L"Module"

#define OUTFLED_OVERLAY_MODULE_NAME64			L"OutfledOverlay64.dll"
#define OUTFLED_OVERLAY_MODULE_NAME32			L"OutfledOverlay.dll"
#define OUTFLED_OVERLAY_DIRECTORY				L"Overlay"


#define OVERLAY_ERROR_UNKNOWN				(DWORD)-1

DWORD SetInGameOverlayStatus(DWORD dwStatus, DWORD dwImageAnchor);
DWORD FindProcessIdByName(LPCWSTR lpszProcessName);

DWORD WINAPI InGameOverlayManager(LPVOID lpParam);
